### PR TITLE
Fix initialization error

### PR DESCRIPTION
**Pull request by rube200**
In the case of moodle directory have a different name

### CODE REVIEW

**Comment by Trojaner** [comment]
When exactly does the modules folder have a different name?

**Comment by rube200** [comment]
When you are using both rocketmod4 and rocketmod5 alternately, it is advisable to have different names, or if for some reason someone wants to change the name of the folder they can do it. (ex: Instead of rocketmod.module for rocketmod)

**Comment by Trojaner** [comment]
Makes sense, did you test the change?

**Comment by rube200** [comment]
Yes, I tested it and it seems to me that everything is fine, this is the version I have installed at the moment

**Pull request merged**
