### PR TITLE
Re-added removed vanish, etc. which was just 2 libraries missing. (LEGACY BRANCH)

### PR DESCRIPTION
**Pull request by persiafighter**
Honestly, it only needed 2 other UnityEngine libraries to compile again without any complain on vanish, or HUD, or anything really... I have no idea why this wasn't done originally, but whatever. Compiles again and no features are randomly removed.

### CODE REVIEW

**Comment by fr34kyn01535** [comment]
Why exactly did you readd HUD.cs? It was just for testing. Before this gets merged the build script must be changed accordingly.

**Comment by persiafighter** [comment]
Because you commented it out on your recent commits and you specified on discord that you did so because it didn't compile:

> PustalorcToday at 3:01 PM
> Sven, may I ask why remove ongui code as well as vanish?
> SvenToday at 3:11 PM
> feel free to fix it
> it didn't compile

"ongui code" was referring to HUD.cs

**Comment by Trojaner** [comment]
HUD.cs was added as a test when Nelson introduced client side modules.
Since client side modules got removed again some months ago, there is no need for it all anymore.

**Comment by persiafighter** [comment]
Removed HUD.cs again in that case then, this time completely and still with the ability to compile Rocket.Unturned.

**Pull request merged**
