### PR TITLE
Fixed UnturnedPlayer.cs - MaxSkills

### PR DESCRIPTION
**Pull request by Teyhota6**
and a couple minor tweaks

### CODE REVIEW

**Comment by fr34kyn01535** [comment]
@Teyhota6 our build environment doesn't run on a windows agent yet, we cant currently use newer C# versions

**Comment by Teyhota6** [comment]
Should be able to now?

**Comment by Trojaner25** [comment]
Should be possible as @fr34kyn01535 said that it runs on Windows CI now

**Comment by Trojaner25** [comment]
Please do another pull request with uptodate repo (resolve conflicts). I will accept ASAP.
Im a bit too lazy to solve the conflicts myself :P

**Pull request closed without merging**
